<a href="https://colab.research.google.com/github/nathalietaylor/Curso-intensivo-Python---Inteligencia-Artificial-UAM/blob/main/Curso_intensivo_Python_(UAM_IA).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Curso intensivo de Python

* Tipos de dados
  * numeros
  * strings
  * impressão
  * listas
  * dicionarios
  * booleanos
  * tuplas
  * sets

* Operadores de comparação
* Declaração if, else, elif
* Laços for
* Laços while
* range()
* Listas
* Funções
* Expressoes lambda
* map e filter
* Métodos


## Tipos de dados


### Números

In [47]:
1 + 1

2

In [48]:
1 * 3

3

In [49]:
3 ** 2

9

In [50]:
4 % 2

0

% para o resto da divisão

In [51]:
1 / 2

0.5

In [52]:
5 // 2

2

#### Atribuição de variáveis

Não podem começar com nº ou caracteres especiais

In [53]:
name_of_var = 2

In [54]:
x = 2
y = 3

In [55]:
z = x + y
z

5

### Strings

diferente do java, que 'char' e "string", Python não diferencia

### Impressão

In [56]:
x = 'hello'

In [57]:
x

'hello'

In [58]:
print(x)

hello


In [59]:
idade = 30
nome = "Nathalie"

In [60]:
print(f"Olá, sou a {nome}, tenho {idade} anos")

Olá, sou a Nathalie, tenho 30 anos


### Listas

In [61]:
[1, 2,3]

[1, 2, 3]

In [62]:
['hi',1, [1,2]]

['hi', 1, [1, 2]]

In [63]:
my_list = ['a','b','c']

In [64]:
my_list

['a', 'b', 'c']

In [65]:
my_list.append('d')
my_list

['a', 'b', 'c', 'd']

In [66]:
my_list[0]

'a'

In [67]:
my_list[3]

'd'

In [68]:
my_list[1:]

['b', 'c', 'd']

In [69]:
my_list[1:3]

['b', 'c']

In [70]:
my_list[:1]

['a']

In [71]:
my_list[0] = "new"

In [72]:
my_list

['new', 'b', 'c', 'd']

In [73]:
nest = [1,2,3,[4,5,['target']]]

In [74]:
nest[3]

[4, 5, ['target']]

In [75]:
nest[3][2]

['target']

In [76]:
nest[3][2][0]

'target'

In [77]:
x = [1,2,3,4]

In [78]:
out = []
for item in x:
  out.append(item**2)
print(out)

[1, 4, 9, 16]


In [79]:
out = []
for item in x:
  out.append(item**2)
  print(out)

[1]
[1, 4]
[1, 4, 9]
[1, 4, 9, 16]


In [80]:
[item**2 for item in x]

[1, 4, 9, 16]

### Dicionário

In [81]:
d = {'key1':'item1', 'key2':'item2'}

In [82]:
d

{'key1': 'item1', 'key2': 'item2'}

In [83]:
d['key1']

'item1'

### Booleanos

In [84]:
True

True

In [85]:
False

False

### Tuplas

objetos do tipo tupla não permite ser alterado

In [86]:
t = (1,2,3)

In [87]:
t[0]

1

In [88]:
t[0] = 'new'

TypeError: 'tuple' object does not support item assignment

### Sets

desconsidera itens repetidos

In [89]:
{1,2,3}

{1, 2, 3}

In [90]:
{1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3}

{1, 2, 3}

## Operadores de comparação

In [ ]:
1==1

In [ ]:
1!=1

In [ ]:
1<2

In [ ]:
1<=2

In [ ]:
1>2

In [ ]:
1>=2

In [ ]:
'hi' =='bye'

## Operadores Logicos

In [ ]:
(1>2) and (2<3)

In [ ]:
(1>2) or (2<3)

In [ ]:
(1==2) or (2==3) or (4==4)

## Desvios condicionais (declarações if, else, elif)

In [93]:
if (1 < 2):
  print('correto')

correto


In [94]:
if (1 > 2):
  print('correto')

In [95]:
if (1 < 2):
  print('correto')
else:
    print('incorreto')

correto


In [96]:
if (1 > 2):
  print('correto')
else:
    print('incorreto')

incorreto


In [97]:
if 1==2:
  print('first')
elif 3==3:
  print('middle')
else:
  print('last')

middle


In [98]:
if 1==2:
  print('first')
elif 3==4:
  print('middle')
else:
  print('last')

last


## Laço for

In [99]:
seq = [1,2,3,4,5]

In [100]:
for item in seq:
  print(item)

1
2
3
4
5


In [101]:
for item in seq:
  print(1)

1
1
1
1
1


In [102]:
for item in seq:
  print(item+item)

2
4
6
8
10


## Laço while

In [103]:
i=1
while i<5:
  print(f'o valor de i é {i}')
  i=i+1

o valor de i é 1
o valor de i é 2
o valor de i é 3
o valor de i é 4


## range()

In [104]:
range(5)

range(0, 5)

In [105]:
for i in range(5):
  print(i)

0
1
2
3
4


In [106]:
list(range(5))

[0, 1, 2, 3, 4]

## Funções

In [107]:
def my_func(param1='defaut'):
  """
  Documentação
  """
  print(param1)

In [108]:
my_func

<function __main__.my_func(param1='defaut')>

In [109]:
my_func()

defaut


In [114]:
my_func('new param')

new param


In [115]:
my_func(param1='new param')

new param


In [116]:
def square(x):
  return x**2

In [117]:
out = square(2)
print(out)

4


## Expressões lambda

função definida temporariamente no meio do código, sem necesisdade de ser declarada

In [118]:

def times2(var):
  return var*2

In [119]:

times2(2)

4

In [120]:

lambda var:var*2

<function __main__.<lambda>(var)>

## map e filter

In [121]:

seq =[1,2,3,4,5]

In [122]:
map(times2,seq)

map aplica função para uma determinada lista, porém retorno não é uma variável, é um ponteiro

In [123]:
list(map(times2,seq))

[2, 4, 6, 8, 10]

In [124]:
list(map(lambda var:var*2,seq))

[2, 4, 6, 8, 10]

In [125]:
filter(lambda item: item%2 == 0, seq)

assim como map indica apenas um endereço de memória

In [126]:
list(filter(lambda item: item%2 == 0, seq))

[2, 4]

## Métodos

### métodos em strings

In [127]:
st = "Olá meu nome é Nathalie"

In [128]:
st.lower()

'olá meu nome é nathalie'

In [129]:
st.upper()

'OLÁ MEU NOME É NATHALIE'

In [130]:
st.split()

['Olá', 'meu', 'nome', 'é', 'Nathalie']

In [131]:
tweet = " Vai Gremio! #Gremio "

In [132]:
tweet.split('#')

[' Vai Gremio! ', 'Gremio ']

In [133]:
email = "nathalietaylorfonoaudiologia@gmail.com"

In [134]:
tweet.split('#')[1]

'Gremio '

In [135]:
email.split('@')

['nathalietaylorfonoaudiologia', 'gmail.com']

In [136]:
email.split('@')[0]

'nathalietaylorfonoaudiologia'

### métodos em dicionários - keys e itens

In [137]:
d = {'key1':'item1', 'key2':'item2'}

In [138]:
d.keys()

dict_keys(['key1', 'key2'])

In [139]:
d.items()

dict_items([('key1', 'item1'), ('key2', 'item2')])

### métodos em listas

In [140]:
lst=[1,2,3]

In [141]:
lst.pop()

3

In [142]:
lst

[1, 2]

In [143]:
'x' in [1,2,3]

False

In [144]:
'x' in ['x', 'y', 'z']

True

# Numpy

O Numpy é uma biblioteca de algebra linear para python. A razão de sua importancia vem do fato de que praticamente todas as bibliotecas do ecossistema Python dependem do Numpy. Além disso ela é rápida pois tem conexões com bibliotecas do C.

Pode-se criar uma array convertendo diretamente uma lista ou listas de lista

In [145]:
import numpy as np

In [3]:
my_list = [1,2,3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Metodos de Construção interna

Existem vários métodos para gerar arrays

### arange

Retorna valores separados igualmente em um dado intervalo
* os dois primeiros agurmento se referem ao intervalo e o terceiro ao número da razão

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

neste caso, exibe de 0 (incluso) a 11(excluso), de dois em dois

### zeros e ones

Gera arrays de zeros e uns

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* caso queira uma matriz contendo de 6, é possível multiplicar por 6

In [12]:
6*np.ones((3,3))

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

### linspace
Retorna números igualmente espaçados em um intervalo específico

* os dois primeiros agurmento se referem ao intervalo e o terceiro ao número de espaçamentos

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

### eye
Cria uma matriz indentidade (cuja a diagonal principal é 1 e os demais elementos 0)

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### randon
o numpy possui várias formas de criar arrays de nºs aleatórios

#### rand

cria uma array na forma dada e popula ela com amostras aleatórias de uma distribuição uniforme entre [0,1)

*[= 0 incluso, ) = 1 excluso

In [15]:
np.random.rand(2)

array([0.66010263, 0.42077141])

In [17]:
np.random.rand(5,5)

array([[0.01804201, 0.72427622, 0.59495608, 0.11203152, 0.3027365 ],
       [0.49681726, 0.74180612, 0.55628128, 0.7304506 , 0.83331519],
       [0.78249332, 0.78830377, 0.72826663, 0.65967783, 0.28376421],
       [0.02151957, 0.28163002, 0.98998017, 0.27204902, 0.66118983],
       [0.5083303 , 0.16751562, 0.55425857, 0.05543164, 0.84598311]])

#### randn
Retorna uma amostra (ou amostras) de uma "distribuição normal padrão". Diferente do rand, que é uniforme

In [19]:
np.random.randn(2,2)

array([[-0.6548352 ,  0.50353037],
       [-0.32974551,  2.03555202]])

In [20]:
np.random.randn(5,5)

array([[ 1.59346859,  1.39478708, -1.1165814 ,  1.45655684, -0.08751506],
       [-2.29391748, -0.86793262, -0.40746771, -0.91151014, -0.43564898],
       [ 0.31699529,  0.80195517, -0.06524569, -0.28158024, -1.89788955],
       [-0.06944102,  0.54244263, -0.70019053, -0.42610265,  1.77031238],
       [ 1.08726401, -1.50114184,  0.77957224,  1.58141431, -0.16792595]])

#### randint

retorna um inteiro aleatório entre low (inclusivo) e high (exclusivo)

In [31]:
np.random.randint(1,100)

21

In [32]:
np.random.randint(1,100,200)

array([63, 38, 41, 85, 99, 62, 52, 75, 77, 73, 13, 85, 66, 96, 83, 45, 27,
       69, 47,  4, 83, 97, 79, 54, 24, 59, 19, 17, 35, 28, 57,  6, 71, 29,
       64, 81, 75, 99, 67, 12, 48, 98, 77, 73, 74, 31, 11, 23, 58, 28, 60,
       30, 66, 96, 16, 69, 77, 53, 94,  8, 14, 88, 71, 19, 22, 60, 38,  7,
       30, 57, 23, 47, 94, 72,  2, 80, 68, 56, 98, 44, 73, 76, 30, 56, 37,
       75, 42, 21, 18, 74, 96, 78, 81, 73,  6, 23, 78, 55, 19, 91, 28, 70,
       51, 95, 59, 46, 99, 99, 55, 14, 33, 77, 11, 86, 77, 88, 88, 24, 70,
       75,  6, 37, 67, 45, 56, 56, 56, 88,  2, 53, 70, 37,  3, 64,  3, 53,
       39, 17, 83, 78, 35, 76, 58, 73, 44, 87, 87, 67, 29, 32,  3, 80, 88,
        9, 17,  9, 19, 36, 48, 89, 61, 13, 24, 71, 41, 88, 40, 65, 21, 85,
       68, 78, 85, 74, 33, 97, 10, 77, 57, 22, 31, 67, 61, 79, 15, 41, 64,
       37, 55, 91, 74, 16, 25, 33, 44, 72,  2, 64, 79, 80])

### Atributos e Métodos Arrays


In [33]:
arr = np.arange(25)
print(arr)
ranarr = np.random.randint(0,50,10)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[ 7 39 21 44 35 28 39 24 24 34]


#### reshape
Retorna uma array contendo a mesma informação com uma nova forma

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### max, min, argmax, argmin
Estes são os métoso úteis para encontrar valores máximos e mínimos, oou para encontrar seu índice de localização utilizando argmax e argmin

In [35]:
ranarr.max()

44

In [36]:
ranarr.argmax()

3

In [37]:
ranarr.min()

7

In [38]:
ranarr.argmin()

0

#### shape
É um atributo que as arrays possuem (não é um método)

In [39]:
arr.shape

(25,)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

arr é um vetor, quando faz reshape, ele passa a ser uma matriz

In [41]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

nesse caso, se tornou uma lista dentro da lista


In [42]:
arr.reshape(1,25).shape

(1, 25)

aqui é como se tivesse virado uma matirz de 1 linha e 25 colunas

In [44]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [45]:
arr.reshape(25,1).shape

(25, 1)

#### dtype
Também possível obter o tipo de dado dos objetos de uma array

In [46]:
arr.dtype

dtype('int64')

##Indexação e Seleção



### Indexação e Seleção e colchetes

A maneira mais simples para obter algum elemento de uma array é similar ao que se faz com as listas

In [110]:
arr[8]

8

In [111]:
arr[2:5]

array([2, 3, 4])

In [112]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [113]:
arr[:5]

array([0, 1, 2, 3, 4])

### Broadcasting
As arrays do numpy deferem de uma lista normal do python por sua capacidade de broadcast

In [146]:
print(arr)
arr[:5] = 100
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[100 100 100 100 100   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24]


In [147]:
arr = np.arange(11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [149]:
slice_of_arr=arr[0:5]
print(slice_of_arr)

[0 1 2 3 4]


In [151]:
slice_of_arr[:] = 99
print(slice_of_arr)

[99 99 99 99 99]


In [152]:
print(arr)

[99 99 99 99 99  5  6  7  8  9 10]


*note que a array original é alterada também

para evitar isso pode-se criar uma copia do array original

In [153]:
arr_copy = arr.copy()
print(arr_copy)

[99 99 99 99 99  5  6  7  8  9 10]


In [156]:
slice_of_copy = arr_copy[:2]
slice_of_copy[:] = 0
print(slice_of_copy)

[0 0]


In [158]:
print (arr)
print (arr_copy)

[99 99 99 99 99  5  6  7  8  9 10]
[ 0  0 99 99 99  5  6  7  8  9 10]


###Indexando uma array 2D (matrizes)

O formato geral é arr_2d[row][col] ou arr_2d[row,col]

In [159]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [160]:
arr_2d[1]

array([20, 25, 30])

In [161]:
arr_2d[1,0]

20

para pegar as 2 primeiras linhas e 2 segundas colunas:

In [162]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

##Operações no Numpy


In [165]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [166]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [167]:
arr * arr #nesse caso multiplica termo a termo, não as matrizes

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [168]:
arr/arr

<ipython-input-168-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [169]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [170]:
arr #não altera a original

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##Funções Universais

In [171]:
np.sqrt(arr) #raiz quadrada

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [175]:
np.exp(arr) #exponencial

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [176]:
np.sin(arr) #seno

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [177]:
np.log(arr)

<ipython-input-177-0a7f062109fe>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])